version: '2'
services:
  certbot:
    build: .
    environment:
    - EMAIL=thomas15v@gmail.com
    - DOMAINS=somkotest.tk
  nginx:
    image: nginx:alpine
    ports:
      - 443:443
      - 80:80
    volumes:
     - ./certbot.conf:/etc/nginx/conf.d/certbot.conf
     - ./default.conf:/etc/nginx/conf.d/site.conf
    links:
     - certbot
    volumes_from:
    - certbot